### ISSUE TITLE
Typo in October 29 Projections

### ISSUE THREAD

**Issue by lematt1991** [shaman-lab/COVID-19Projection#8]
Hi, I'm seeing what seems to be a typo in the October 29th Projections, such as [this](https://raw.githubusercontent.com/shaman-lab/COVID-19Projection/master/Projection_October29/Projection_5_1xhold.csv) one.  The year in the date is "0020", instead of "2020"

**Comment by tkcy** [comment]
@lematt1991 Thanks, this has been corrected

**Comment by lematt1991** [comment]
Thanks for the quick reply!  I think [this](https://raw.githubusercontent.com/shaman-lab/COVID-19Projection/master/Projection_October29/Projection_reduce10-sph-tky2104-ehs.csv) might still have the problem (but the rest look good to me!)

**Comment by tkcy** [comment]
@lematt1991  Thanks for catching that stray file -  it's a duplicate and has been deleted.  Thanks!
